import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import process from 'node:process';

const requiredFiles = ['manifest.json', 'main.js', 'styles.css', 'versions.json'];
const forbiddenRootFiles = ['data.json', 'main.js.map', 'styles.css.map'];
const failures = [];

for (const file of requiredFiles) {
	if (!existsSync(file)) {
		failures.push(`Missing ${file}`);
		continue;
	}
	if (statSync(file).size === 0) {
		failures.push(`${file} is empty`);
	}
}

const manifest = JSON.parse(readFileSync('manifest.json', 'utf8'));
const versions = JSON.parse(readFileSync('versions.json', 'utf8'));
const packageJson = JSON.parse(readFileSync('package.json', 'utf8'));
const readme = readFileSync('README.md', 'utf8');
const bundle = readFileSync('main.js', 'utf8');

if (manifest.id !== 'ai-knowledge-organizer') {
	failures.push(`Unexpected manifest id: ${manifest.id}`);
}

if (manifest.version !== packageJson.version) {
	failures.push(
		`manifest.json version ${manifest.version} does not match package.json version ${packageJson.version}`,
	);
}

if (versions[manifest.version] !== manifest.minAppVersion) {
	failures.push(
		`versions.json missing ${manifest.version}: ${manifest.minAppVersion}`,
	);
}

if (manifest.isDesktopOnly !== false) {
	failures.push('manifest.json must declare isDesktopOnly false for mobile compatibility.');
}

if (packageJson.main !== 'main.js') {
	failures.push('package.json main must point to main.js.');
}

if (!readme.includes(manifest.name)) {
	failures.push('README.md must include the manifest plugin name.');
}

if (!readme.includes(manifest.id)) {
	failures.push('README.md must include the manifest plugin id.');
}

if (!bundle.startsWith('/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD')) {
	failures.push('main.js must look like the generated esbuild bundle.');
}

if (!bundle.includes('require("obsidian")')) {
	failures.push('main.js must externalize the Obsidian API instead of bundling it.');
}

if (bundle.includes('sourceMappingURL') || bundle.includes('sourcesContent')) {
	failures.push('main.js must be a production build without embedded sourcemaps.');
}

for (const file of forbiddenRootFiles) {
	if (existsSync(file)) {
		failures.push(`Forbidden release-adjacent file at repository root: ${file}`);
	}
}

for (const file of readdirSync('.')) {
	if (file.endsWith('.map')) {
		failures.push(`Sourcemap file should not be present at repository root: ${file}`);
	}
}

if (failures.length > 0) {
	for (const failure of failures) {
		console.error(`release-check: ${failure}`);
	}
	process.exit(1);
}

console.log(
	`release-check: ${manifest.name} ${manifest.version} has required release files.`,
);
